# Generated by Django 5.0.2 on 2024-03-11 20:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gym', '0004_auto_20200911_0721'),
    ]

    operations = [
        migrations.CreateModel(
            name='Trainer',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('contact', models.CharField(max_length=12, unique=True)),
                ('email', models.CharField(max_length=50, unique=True)),
                ('age', models.IntegerField(max_length=40)),
                ('gender', models.CharField(choices=[('M', 'Male'), ('F', 'Female'), ('O', 'Other')], max_length=1)),
                ('instalink', models.CharField(max_length=500)),
                ('xlink', models.CharField(max_length=400)),
                ('facebooklink', models.CharField(max_length=400)),
                ('profile_pic', models.ImageField(blank=True, upload_to='trainer_pics')),
            ],
        ),
    ]
